## Nunmpy Phase-1

In [19]:
import numpy as np

### Creating Array from List

In [20]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : \n", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : \n", arr_2d)

1D array : 
 [1 2 3 4 5]
2D array : 
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [21]:
py_list = [1,2,3]
print("Python list multiplication : " , py_list * 2)

np_array = np.array([1,2,3])
print("Numpy array multiplication : ", np_array*2) # element wise multiplication 


Python list multiplication :  [1, 2, 3, 1, 2, 3]
Numpy array multiplication :  [2 4 6]


### Creating array form scratch

In [22]:
zeros = np.zeros((3,4))
print("Zeros Array : \n", zeros)

ones = np.ones((3,4))
print("Ones Array : \n", ones)

full = np.full((3,4),5) #.full((row,column),intitNumber)
print("Full Array : \n", full)

random = np.random.random((3,4)) 
print("Random Array : \n", random)

sequence = np.arange(0,10,2) #.arange(start,stop,step)
print("Zeros Array : \n", sequence)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Random Array : 
 [[0.44508503 0.38969599 0.95559441 0.98779287]
 [0.47568133 0.56239714 0.84500834 0.77085517]
 [0.04243558 0.78669202 0.02848134 0.70363002]]
Zeros Array : 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [23]:
vector = np.array([1,2,3])
print("Vector : \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : \n", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor : \n", tensor)

Vector : 
 [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [24]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("Datatype : ", arr.dtype)



Shape :  (2, 3)
Dimension :  2
Size :  6
Datatype :  int64


### Array Reshaping

In [25]:
arr = np.arange(12);
print("Original Array : ",arr);

reshaped = arr.reshape((3,4))
print("Reshaped Array : \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array : \n", flattened)

raveled = reshaped.ravel() # it returns view instead of copy
print("Raveled Array : \n", raveled)

transposed = reshaped.T
print("Transposed Array : \n", transposed)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Numpy Phase-2

In [26]:
import numpy as np

### Selecting And Slicing 

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing : ",arr[2:7])
print("With Step Slicing : ",arr[1:8:2])
print("Negative Indexing : ",arr[-3])

Basic Slicing :  [3 4 5 6 7]
With Step Slicing :  [2 4 6 8]
Negative Indexing :  8


In [28]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element : ", arr_2d[0,2]) #[row,column]
print("Entire Row : ", arr_2d[1]) #[row,column]
print("Entire Col : ", arr_2d[:,1]) #ignore with :,

Specific Element :  3
Entire Row :  [4 5 6]
Entire Col :  [2 5 8]


### Sorting

In [29]:
unsorted = np.array([3,9,4,5,7,2,6,10,1,4])
print("Sorted Array : ", np.sort(unsorted))

array_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d Array by column : \n", np.sort(array_2d_unsorted, axis=0))


Sorted Array :  [ 1  2  3  4  4  5  6  7  9 10]
Sorted 2d Array by column : 
 [[1 1]
 [2 2]
 [3 3]]


### Filtering

In [30]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even number filtering : " , even_numbers)


Even number filtering :  [ 2  4  6  8 10]


### Filter With Masks

In [31]:
masks = numbers > 5
print("Numbers greater than 5 ", numbers[masks])

Numbers greater than 5  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [32]:
indices = [0,2,4]
print("Printing Element with array of indexes : ",numbers[indices]) #passing array of indexes to print the array

where_result = np.where(numbers > 5)
print("Np where : ", numbers[where_result])

condition_array = np.where(numbers > 5 , numbers * 2 , numbers)
print("Condition Array : ", condition_array);

Printing Element with array of indexes :  [1 3 5]
Np where :  [ 6  7  8  9 10]
Condition Array :  [ 1  2  3  4  5 12 14 16 18 20]


### Adding and Remove Data

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2)) # [arr1] + [arr2] = [...arr1,...arr2]
print("Combined Array : " , combined)

Combined Array :  [1 2 3 4 5 6]


### Array Compatibility

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shape : ",a.shape == b.shape)

Compatibility Shape :  True


In [35]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row)) #.vstack adds a new row
print("Original : \n",original)
print("With new row : \n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new col : \n", with_new_col)

Original : 
 [[1 2]
 [3 4]]
With new row : 
 [[1 2]
 [3 4]
 [5 6]]
With new col : 
 [[1 2 7]
 [3 4 8]]


In [36]:
array = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)

print("Array after deletion : ", deleted)

Array after deletion :  [ 1  2  4  5  6  7  8  9 10]
